### ISSUE TITLE
Spring源码深度解析（第2版）

### ISSUE THREAD

**Issue by qinggeng2015** [DeppWang/Java-Books#1]
hi，我这里有一本电子书（非扫描版），上传报错，查了一下说fork的仓库无法用lfs上传大文件，但是原仓库可以。

`batch response: @yklove can not upload new objects to public fork yklove/Java-Books
`
直接传到了网盘上了，可以试一下能不能上传
https://share.weiyun.com/5gHFuZ0

**Comment by adinghub** [comment]
可否再次分享一下？谢谢

**Comment by qinggeng2015** [comment]
> 可以否再次分享一下？谢谢

留一下邮箱，我直接发给你吧
